trigger:
- main

variables:
  TF_LOG: INFO
  TF_LOG_PATH: terraform.log

pool:
  name: Default
  vmImage: ubuntu-latest
  demands:
  - Agent.Name -equals 	mac-ubuntu

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.13.3'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
    KeyVaultName: 'bestrong-keyvault-3'
    SecretsFilter: 'db-password'
    RunAsPreJob: true

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'
    backendServiceArm: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
    backendAzureRmStorageAccountName: 'bestrongtfstate1'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'
    environmentServiceNameAzureRM: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
  env:
    TF_VAR_db_password: $(db_password)