trigger:
- main

pr: none

variables:
  TF_LOG: TRACE
  TF_LOG_PATH: terraform.log

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.13.3'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
    KeyVaultName: 'bestrong-keyvault-3'
    SecretsFilter: 'db-password'
    RunAsPreJob: true

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'
    backendServiceArm: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
    backendAzureRmStorageAccountName: 'bestrongtfstate1'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'
    commandOptions: "-input=false"

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_dir'
    environmentServiceNameAzureRM: 'Azure for Students(9eb5184c-5f9e-4785-99c3-744581f619cf)'
    commandOptions: "-parallelism=1 -input=false -lock-timeout=10m"

  env:
    TF_VAR_db_password: $(db_password)